workspace:
  base: /go
  path: src/github.com/drone/drone

pipeline:
  test:
    image: golang:1.8
    commands:
      - make deps gen
      - make test test_postgres test_mysql

  compile:
    image: golang:1.8
    commands:
      - export PATH=$PATH:/go/bin
      - make build
    when:
      event: push

  archive:
    image: plugins/s3
    acl: public-read
    bucket: downloads.drone.io
    source: release/**/*.*
    target: /0.6.0/
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: push
      branch: master

  trigger:
    image: plugins/downstream
    server: https://beta.drone.io
    fork: true
    secrets: [ downstream_token ]
    repositories: drone/drone-enterprise
    when:
      branch: master
      event: push

  notify:
    image: plugins/gitter
    dummy: true # todo remove this
    secrets: [ gitter_webhook ]
    when:
      status: [ success, failure ]

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
