image: go1.2
script:
  - make deps
  - make
  - make test
  - make dpkg
notify:
  email:
    recipients:
      - brad@drone.io

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: downloads.drone.io
    access_key: $AWS_KEY
    secret_key: $AWS_SECRET
    source: /tmp/drone.deb
    target: latest/