workspace:
  base: /go
  path: src/github.com/drone/drone

pipeline:
  test:
    image: golang:1.8
    commands:
      - make deps gen
      - make test test_postgres test_mysql

  compile:
    image: golang:1.8
    commands:
      - export PATH=$PATH:/go/bin
      - make build
    when:
      event: push

  archive:
    image: plugins/s3
    acl: public-read
    bucket: downloads.drone.io
    source: release/**/*.*
    target: /0.6.0/
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    secrets: [ aws_access_key_id, aws_secret_access_key ]
    when:
      event: push
      branch: master

  publish:
    image: plugins/docker
    repo: drone/drone
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    secrets: [ docker_username, docker_password ]
    tag: [ latest, 0.6, 0.6.0, 0.6.0-rc.1 ]
    when:
      branch: master
      event: push

  notify:
    image: plugins/gitter
    webhook: ${GITTER_WEBHOOK}
    secrets: [ gitter_webhook ]
    when:
      status: [ success, failure ]
      event: [ push, pull_request ]

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_USER=postgres
  mysql:
    image: mysql:5.6.27
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
